name: Deploy to aws eks

on:
  push:
    branches: [main]
    
  workflow_dispatch:
  
jobs:
  gradle_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build

    - name: copy *.war file to Dockerfile
      run: |
        cp ./build/libs/*.war ./Dockerfile
  
  docker_build_push:
    uses: seunghayim/m-dev/.github/workflows/docker.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
