name: Build Docker Container & Push to DO Registry

on:
  push:
    branches: [main]

jobs:
  gradle_build:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradle executable
      run: chmod +x ./gradlew

    - name: Execute Gradle build
      run: ./gradlew build

    - name: copy *.war file to Dockerfile
      run: |
        cp ./build/libs/*.war ./Dockerfile
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./Dockerfile
        push: true
        tags: |
         ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
         ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{github.sha::7}}-${{github.run_number}}
