name: Java CI with Gradle

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
        
    - name: check build
      run: ls ./build/libs
           
    - name: check docker ps
      run: docker ps
            
    - name: copy *.war file to Dockerfile
      run: |
        cp ./build/libs/*.war ./Dockerfile
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      working-directory: ./Dockerfile
      run: |
        docker build -f Dockerfile \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:latest \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} . \
    - name: Push image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev --all-tags
     
    - name: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_TOKEN }}'

    - name: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: 'langhae'
        location: 'us-central1-c'
        
    - name: Update Deployment image
      run: kubectl set image deployment/was-deploy java=${{ secrets.DOCKERHUB_USERNAME }}/m-dev:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
    - name: See the rollout status
      run: kubectl rollout status deployment/was-deploy
  
