name: Deploy to aws eks

on:
  push:
    branches: [main]
    
  workflow_call:

jobs:
  docker_build_push:
    uses: seunghayim/m-dev/.github/workflows/docker.yml@main
    secrets:
      envPAT: |
       ${{ secrets.DOCKERHUB_USERNAME }}
       ${{ secrets.DOCKERHUB_TOKEN }}
